//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImprintValues {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImprintValues() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ImprintValues", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerd Herbst.
        /// </summary>
        internal static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRA 2984.
        /// </summary>
        internal static string CommercialRegisterEntry {
            get {
                return ResourceManager.GetString("CommercialRegisterEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andreas Prechtl.
        /// </summary>
        internal static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle auf dieser Internetpräsenz verwendeten Inhalte (Skripte, Layouts, Fotos, etc.) sind urheberrechtlich geschützt. Sollten Sie Teile hiervon verwenden wollen, wenden Sie sich bitte an den jeweiligen Inhaber oder den Seitenbetreiber..
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andreas Prechtl.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich..
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Inhalte unserer Seiten wurden mit gr&amp;#246;&amp;#223;ter Sorgfalt erstellt.
        ///        F&amp;#252;r die Richtigkeit, Vollst&amp;#228;ndigkeit und Aktualit&amp;#228;t der Inhalte 
        ///        k&amp;#246;nnen wir jedoch keine Gew&amp;#228;hr &amp;#252;bernehmen.
        ///        Als Diensteanbieter sind wir gem&amp;#228;&amp;#223; &amp;#167; 7 Abs.1 TMG f&amp;#252;r 
        ///        eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. &amp;lt;br /&amp;gt;
        ///        Nach &amp;#167;&amp;#167; 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht 
        ///        verpflichte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExtraContent {
            get {
                return ResourceManager.GetString("ExtraContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einzelunternehmung.
        /// </summary>
        internal static string LegalForm {
            get {
                return ResourceManager.GetString("LegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerd Herbst, &lt;a href=&quot;http://www.sulzbacher-satz-studio.de&quot;&gt;Sulzbacher-Satz-Studio / Jürgen Gradl&lt;/a&gt;.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Nutzung unserer Seite ist in der Regel ohne Angabe personenbezogener Daten m&amp;#246;glich.&amp;lt;br /&amp;gt;
        ///        Soweit auf unseren Seiten personenbezogene Daten (beispielsweise Name, 
        ///        Anschrift oder eMail-Adressen) erhoben werden, erfolgt dies - wenn m&amp;#246;glich - auf freiwilliger Basis. &amp;lt;br /&amp;gt;
        ///        Diese Daten werden ohne Ihre ausdr&amp;#252;ckliche Zustimmung nicht an Dritte weitergegeben. 
        ///        &amp;lt;br /&amp;gt;
        ///        Jedoch erheben und verwenden wir zur statistischen Erhebung und technisc [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andreas Prechtl.
        /// </summary>
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amberg.
        /// </summary>
        internal static string RegisterCourt {
            get {
                return ResourceManager.GetString("RegisterCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Finanzamt Amberg.
        /// </summary>
        internal static string TaxId {
            get {
                return ResourceManager.GetString("TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE203095280.
        /// </summary>
        internal static string VATId {
            get {
                return ResourceManager.GetString("VATId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerd Herbst.
        /// </summary>
        internal static string WebsiteContentEditor {
            get {
                return ResourceManager.GetString("WebsiteContentEditor", resourceCulture);
            }
        }
    }
}
