//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Imprint {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Imprint() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Imprint", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschäftsführer.
        /// </summary>
        internal static string CEO {
            get {
                return ResourceManager.GetString("CEO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handelsregistereintrag.
        /// </summary>
        internal static string CommercialRegisterEntry {
            get {
                return ResourceManager.GetString("CommercialRegisterEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konzept.
        /// </summary>
        internal static string Concept {
            get {
                return ResourceManager.GetString("Concept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhalt.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urheberrecht.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        internal static string Design {
            get {
                return ResourceManager.GetString("Design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haftungsausschluss.
        /// </summary>
        internal static string Disclaimer {
            get {
                return ResourceManager.GetString("Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtliches.
        /// </summary>
        internal static string Legal {
            get {
                return ResourceManager.GetString("Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschäftsform.
        /// </summary>
        internal static string LegalForm {
            get {
                return ResourceManager.GetString("LegalForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotos.
        /// </summary>
        internal static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datenschutz.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programmierung.
        /// </summary>
        internal static string Programming {
            get {
                return ResourceManager.GetString("Programming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registergericht.
        /// </summary>
        internal static string RegisterCourt {
            get {
                return ResourceManager.GetString("RegisterCourt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steuernummer.
        /// </summary>
        internal static string TaxId {
            get {
                return ResourceManager.GetString("TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressum.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Umsatzsteuer-Id gemäß §27 a Umsatzsteuergesetz.
        /// </summary>
        internal static string VATId {
            get {
                return ResourceManager.GetString("VATId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verantwortlicher für den Inhalt im Sinne des § 55 RStV.
        /// </summary>
        internal static string WebsiteContentEditor {
            get {
                return ResourceManager.GetString("WebsiteContentEditor", resourceCulture);
            }
        }
    }
}
